version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      DB_NAME: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bundle exec rails s -p 6969 -b '0.0.0.0'
    ports:
      - "6969:6969"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
volumes:
  dbdata:
